import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';

interface WordExportRequest {
  content: string;
  title: string;
  type: 'personal_statement' | 'cover_letter' | 'sop' | 'cv';
  metadata?: {
    author?: string;
    date?: string;
    institution?: string;
  };
}

export const POST: RequestHandler = async ({ request, locals: { supabase } }) => {
  const { data: { session } } = await supabase.auth.getSession();
  
  if (!session?.user) {
    return json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const exportData: WordExportRequest = await request.json();
    const { content, title, type, metadata } = exportData;

    if (!content || !title) {
      return json({ error: 'Content and title are required' }, { status: 400 });
    }

    // Create RTF content that Word can open
    // RTF (Rich Text Format) is supported by Word and is easier to generate than DOCX
    const rtfContent = `{\\rtf1\\ansi\\deff0
{\\fonttbl{\\f0 Times New Roman;}}
{\\colortbl;\\red0\\green0\\blue0;\\red102\\green102\\blue102;}

\\f0\\fs24

{\\qc\\b\\fs32 ${title}\\par}
${metadata?.author ? `{\\qc\\fs20 by ${metadata.author}\\par}` : ''}
${metadata?.institution ? `{\\qc\\fs20 ${metadata.institution}\\par}` : ''}
${metadata?.date ? `{\\qc\\fs20 ${metadata.date}\\par}` : ''}

\\par\\par

\\ql\\fs24
${content.split('\n\n').map(paragraph => 
  paragraph.trim() ? paragraph.replace(/\n/g, '\\line ') + '\\par\\par' : ''
).join('')}

\\par\\par

{\\qc\\cf2\\fs18 Generated by Abroaducate on ${new Date().toLocaleDateString()}\\par}
{\\qc\\cf2\\fs18 Visit abroaducate.com for more academic application tools\\par}

}`;
    
    // Log the export activity
    try {
      const analyticsTable = type === 'personal_statement' ? 'personal_statement_analytics' : 
                           type === 'cover_letter' ? 'cover_letter_analytics' : 
                           'sop_analytics';
      
      await supabase
        .from(analyticsTable)
        .insert({
          user_id: session.user.id,
          action_type: 'exported_word',
          session_data: { 
            title: title,
            format: 'rtf',
            exported_at: new Date().toISOString()
          }
        });
    } catch (analyticsError) {
      console.warn('Analytics logging failed:', analyticsError);
      // Don't fail the export for analytics issues
    }

    return new Response(rtfContent, {
      headers: {
        'Content-Type': 'application/rtf',
        'Content-Disposition': `attachment; filename="${title.replace(/[^a-z0-9\s]/gi, '').replace(/\s+/g, '_').toLowerCase()}.rtf"`
      }
    });

  } catch (error) {
    console.error('Error exporting Word document:', error);
    return json({ 
      error: 'Word export failed',
      details: error instanceof Error ? error.message : 'Unknown error'
    }, { status: 500 });
  }
}; 