// Generated by Wrangler by running `wrangler types`

interface Env {
	APP_URL: "https://www.abroaducate.com";
	CUSTOMER_IO_SITE_ID: "eb9a57e20d1cb3575cb7";
	PUBLIC_SUPABASE_URL: "https://yiubrielkgrzcwdabepp.supabase.co";
	PUBLIC_TURNSTILE_SITE_KEY: "0x4AAAAAADkCMjugixsEMUM4";
	ASSETS: Fetcher;
}
