name = "abroaducate"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[vars]
APP_URL = "https://www.abroaducate.com"
CUSTOMER_IO_SITE_ID = "eb9a57e20d1cb3575cb7"
