// UK University Database Integration System
// Phase 2.2: International Expansion - UK Universities

import type { EnhancedUniversity } from './university-integration';

// UK University Rankings Data (Based on Guardian 2025, Complete University Guide, etc.)
export interface UKUniversityData {
    id: string;
    name: string;
    location: string;
    region: string;
    established: number;
    ranking_guardian: number;
    ranking_complete_guide: number;
    ranking_times: number;
    acceptance_rate: number;
    student_satisfaction_teaching: number;
    student_satisfaction_feedback: number;
    student_staff_ratio: number;
    entry_tariff: number;
    graduate_prospects: number;
    tuition_fees_uk: number;
    tuition_fees_international: number;
    accommodation_cost: number;
    total_students: number;
    international_students_percentage: number;
    research_quality: string;
    university_type: 'ancient' | 'red_brick' | 'plate_glass' | 'new' | 'post_1992' | 'specialist';
    notable_strengths: string[];
    popular_subjects: string[];
    website: string;
    ucas_code?: string;
}

// Top 50 UK Universities Database (2025 Data)
export const UK_UNIVERSITIES: UKUniversityData[] = [
    {
        id: 'oxford',
        name: 'University of Oxford',
        location: 'Oxford',
        region: 'South East England',
        established: 1096,
        ranking_guardian: 1,
        ranking_complete_guide: 1,
        ranking_times: 1,
        acceptance_rate: 17.5,
        student_satisfaction_teaching: 94.3,
        student_satisfaction_feedback: 75.6,
        student_staff_ratio: 10.3,
        entry_tariff: 203,
        graduate_prospects: 93,
        tuition_fees_uk: 9250,
        tuition_fees_international: 37510,
        accommodation_cost: 8500,
        total_students: 24515,
        international_students_percentage: 45,
        research_quality: 'world_leading',
        university_type: 'ancient',
        notable_strengths: ['academic-tradition', 'research-excellence', 'global-reputation', 'prestigious-faculty'],
        popular_subjects: ['Philosophy', 'Politics', 'Economics', 'Law', 'Medicine', 'History', 'English Literature'],
        website: 'https://www.ox.ac.uk',
        ucas_code: 'O33'
    },
    {
        id: 'cambridge',
        name: 'University of Cambridge',
        location: 'Cambridge',
        region: 'East of England',
        established: 1209,
        ranking_guardian: 3,
        ranking_complete_guide: 2,
        ranking_times: 2,
        acceptance_rate: 21.0,
        student_satisfaction_teaching: 92.1,
        student_satisfaction_feedback: 74.2,
        student_staff_ratio: 11.6,
        entry_tariff: 208,
        graduate_prospects: 94,
        tuition_fees_uk: 9250,
        tuition_fees_international: 37293,
        accommodation_cost: 7200,
        total_students: 23247,
        international_students_percentage: 39,
        research_quality: 'world_leading',
        university_type: 'ancient',
        notable_strengths: ['research-excellence', 'academic-tradition', 'innovation', 'prestigious-faculty'],
        popular_subjects: ['Mathematics', 'Natural Sciences', 'Engineering', 'Computer Science', 'Medicine', 'Economics'],
        website: 'https://www.cam.ac.uk',
        ucas_code: 'C05'
    },
    {
        id: 'st-andrews',
        name: 'University of St Andrews',
        location: 'St Andrews',
        region: 'Scotland',
        established: 1413,
        ranking_guardian: 2,
        ranking_complete_guide: 3,
        ranking_times: 3,
        acceptance_rate: 13.0,
        student_satisfaction_teaching: 92.6,
        student_satisfaction_feedback: 80.9,
        student_staff_ratio: 11.9,
        entry_tariff: 212,
        graduate_prospects: 91,
        tuition_fees_uk: 9250,
        tuition_fees_international: 30160,
        accommodation_cost: 6800,
        total_students: 12047,
        international_students_percentage: 50,
        research_quality: 'excellent',
        university_type: 'ancient',
        notable_strengths: ['international-community', 'small-class-sizes', 'academic-excellence', 'historic-setting'],
        popular_subjects: ['International Relations', 'Economics', 'Psychology', 'English', 'History', 'Philosophy'],
        website: 'https://www.st-andrews.ac.uk',
        ucas_code: 'S36'
    },
    {
        id: 'lse',
        name: 'London School of Economics',
        location: 'London',
        region: 'London',
        established: 1895,
        ranking_guardian: 4,
        ranking_complete_guide: 4,
        ranking_times: 4,
        acceptance_rate: 12.9,
        student_satisfaction_teaching: 87.0,
        student_satisfaction_feedback: 72.1,
        student_staff_ratio: 12.8,
        entry_tariff: 192,
        graduate_prospects: 93,
        tuition_fees_uk: 9250,
        tuition_fees_international: 25608,
        accommodation_cost: 12500,
        total_students: 12330,
        international_students_percentage: 70,
        research_quality: 'world_leading',
        university_type: 'specialist',
        notable_strengths: ['social-sciences', 'economics', 'political-science', 'global-network'],
        popular_subjects: ['Economics', 'Politics', 'International Relations', 'Finance', 'Law', 'Sociology'],
        website: 'https://www.lse.ac.uk',
        ucas_code: 'L72'
    },
    {
        id: 'imperial',
        name: 'Imperial College London',
        location: 'London',
        region: 'London',
        established: 1907,
        ranking_guardian: 5,
        ranking_complete_guide: 5,
        ranking_times: 5,
        acceptance_rate: 14.3,
        student_satisfaction_teaching: 85.5,
        student_satisfaction_feedback: 64.4,
        student_staff_ratio: 11.9,
        entry_tariff: 204,
        graduate_prospects: 96,
        tuition_fees_uk: 9250,
        tuition_fees_international: 40940,
        accommodation_cost: 11000,
        total_students: 19945,
        international_students_percentage: 58,
        research_quality: 'world_leading',
        university_type: 'specialist',
        notable_strengths: ['science-technology', 'research-excellence', 'industry-connections', 'innovation'],
        popular_subjects: ['Engineering', 'Medicine', 'Computer Science', 'Physics', 'Chemistry', 'Mathematics'],
        website: 'https://www.imperial.ac.uk',
        ucas_code: 'I50'
    },
    {
        id: 'durham',
        name: 'Durham University',
        location: 'Durham',
        region: 'North East England',
        established: 1832,
        ranking_guardian: 6,
        ranking_complete_guide: 6,
        ranking_times: 6,
        acceptance_rate: 13.6,
        student_satisfaction_teaching: 87.9,
        student_satisfaction_feedback: 74.2,
        student_staff_ratio: 13.5,
        entry_tariff: 185,
        graduate_prospects: 91,
        tuition_fees_uk: 9250,
        tuition_fees_international: 28500,
        accommodation_cost: 7500,
        total_students: 21000,
        international_students_percentage: 25,
        research_quality: 'excellent',
        university_type: 'ancient',
        notable_strengths: ['collegiate-system', 'academic-excellence', 'beautiful-campus', 'traditions'],
        popular_subjects: ['Business', 'Law', 'History', 'English', 'Geography', 'Psychology'],
        website: 'https://www.durham.ac.uk',
        ucas_code: 'D86'
    },
    {
        id: 'bath',
        name: 'University of Bath',
        location: 'Bath',
        region: 'South West England',
        established: 1966,
        ranking_guardian: 7,
        ranking_complete_guide: 7,
        ranking_times: 7,
        acceptance_rate: 17.1,
        student_satisfaction_teaching: 88.0,
        student_satisfaction_feedback: 72.8,
        student_staff_ratio: 15.3,
        entry_tariff: 180,
        graduate_prospects: 92,
        tuition_fees_uk: 9250,
        tuition_fees_international: 25000,
        accommodation_cost: 6800,
        total_students: 18857,
        international_students_percentage: 35,
        research_quality: 'excellent',
        university_type: 'plate_glass',
        notable_strengths: ['engineering', 'management', 'architecture', 'graduate-prospects'],
        popular_subjects: ['Engineering', 'Management', 'Architecture', 'Computer Science', 'Economics', 'Psychology'],
        website: 'https://www.bath.ac.uk',
        ucas_code: 'B16'
    },
    {
        id: 'warwick',
        name: 'University of Warwick',
        location: 'Coventry',
        region: 'West Midlands',
        established: 1965,
        ranking_guardian: 8,
        ranking_complete_guide: 8,
        ranking_times: 8,
        acceptance_rate: 16.9,
        student_satisfaction_teaching: 88.5,
        student_satisfaction_feedback: 76.1,
        student_staff_ratio: 13.9,
        entry_tariff: 179,
        graduate_prospects: 89,
        tuition_fees_uk: 9250,
        tuition_fees_international: 29050,
        accommodation_cost: 6500,
        total_students: 27331,
        international_students_percentage: 42,
        research_quality: 'excellent',
        university_type: 'plate_glass',
        notable_strengths: ['business-school', 'research-intensive', 'industry-links', 'innovation'],
        popular_subjects: ['Business', 'Economics', 'Engineering', 'Computer Science', 'Mathematics', 'Politics'],
        website: 'https://warwick.ac.uk',
        ucas_code: 'W20'
    },
    {
        id: 'ucl',
        name: 'University College London',
        location: 'London',
        region: 'London',
        established: 1826,
        ranking_guardian: 9,
        ranking_complete_guide: 9,
        ranking_times: 9,
        acceptance_rate: 29.5,
        student_satisfaction_teaching: 84.2,
        student_satisfaction_feedback: 69.7,
        student_staff_ratio: 10.9,
        entry_tariff: 183,
        graduate_prospects: 90,
        tuition_fees_uk: 9250,
        tuition_fees_international: 35000,
        accommodation_cost: 10500,
        total_students: 48919,
        international_students_percentage: 53,
        research_quality: 'world_leading',
        university_type: 'red_brick',
        notable_strengths: ['research-intensive', 'diverse-community', 'london-location', 'innovation'],
        popular_subjects: ['Medicine', 'Engineering', 'Architecture', 'Psychology', 'Economics', 'Law'],
        website: 'https://www.ucl.ac.uk',
        ucas_code: 'U80'
    },
    {
        id: 'loughborough',
        name: 'Loughborough University',
        location: 'Loughborough',
        region: 'East Midlands',
        established: 1966,
        ranking_guardian: 10,
        ranking_complete_guide: 10,
        ranking_times: 10,
        acceptance_rate: 23.8,
        student_satisfaction_teaching: 87.6,
        student_satisfaction_feedback: 75.6,
        student_staff_ratio: 14.1,
        entry_tariff: 162,
        graduate_prospects: 89,
        tuition_fees_uk: 9250,
        tuition_fees_international: 27250,
        accommodation_cost: 6200,
        total_students: 19500,
        international_students_percentage: 25,
        research_quality: 'excellent',
        university_type: 'plate_glass',
        notable_strengths: ['sports-excellence', 'engineering', 'design', 'student-experience'],
        popular_subjects: ['Sport Science', 'Engineering', 'Business', 'Design', 'Computer Science', 'Media'],
        website: 'https://www.lboro.ac.uk',
        ucas_code: 'L79'
    },

    // RUSSELL GROUP UNIVERSITIES (Additional)
    {
        id: 'edinburgh',
        name: 'University of Edinburgh',
        location: 'Edinburgh',
        region: 'Scotland',
        established: 1583,
        ranking_guardian: 11,
        ranking_complete_guide: 11,
        ranking_times: 11,
        acceptance_rate: 18.5,
        student_satisfaction_teaching: 85.2,
        student_satisfaction_feedback: 71.4,
        student_staff_ratio: 12.8,
        entry_tariff: 185,
        graduate_prospects: 88,
        tuition_fees_uk: 9250,
        tuition_fees_international: 34800,
        accommodation_cost: 7500,
        total_students: 47000,
        international_students_percentage: 45,
        research_quality: 'world_leading',
        university_type: 'ancient',
        notable_strengths: ['research-excellence', 'historic-prestige', 'international-reputation', 'festival-city'],
        popular_subjects: ['Medicine', 'Law', 'Engineering', 'Arts', 'Sciences', 'Business'],
        website: 'https://www.ed.ac.uk',
        ucas_code: 'E84'
    },
    {
        id: 'kings-college',
        name: "King's College London",
        location: 'London',
        region: 'London',
        established: 1829,
        ranking_guardian: 12,
        ranking_complete_guide: 12,
        ranking_times: 12,
        acceptance_rate: 25.4,
        student_satisfaction_teaching: 83.8,
        student_satisfaction_feedback: 68.9,
        student_staff_ratio: 11.7,
        entry_tariff: 178,
        graduate_prospects: 89,
        tuition_fees_uk: 9250,
        tuition_fees_international: 35000,
        accommodation_cost: 10800,
        total_students: 41000,
        international_students_percentage: 48,
        research_quality: 'world_leading',
        university_type: 'red_brick',
        notable_strengths: ['medical-school', 'london-location', 'research-intensive', 'global-reputation'],
        popular_subjects: ['Medicine', 'Law', 'International Relations', 'Psychology', 'English', 'History'],
        website: 'https://www.kcl.ac.uk',
        ucas_code: 'K60'
    },
    {
        id: 'manchester',
        name: 'University of Manchester',
        location: 'Manchester',
        region: 'North West England',
        established: 1824,
        ranking_guardian: 13,
        ranking_complete_guide: 13,
        ranking_times: 13,
        acceptance_rate: 28.7,
        student_satisfaction_teaching: 84.5,
        student_satisfaction_feedback: 72.1,
        student_staff_ratio: 14.2,
        entry_tariff: 169,
        graduate_prospects: 87,
        tuition_fees_uk: 9250,
        tuition_fees_international: 28000,
        accommodation_cost: 6800,
        total_students: 46000,
        international_students_percentage: 42,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['research-powerhouse', 'large-student-body', 'industry-links', 'vibrant-city'],
        popular_subjects: ['Engineering', 'Computer Science', 'Business', 'Medicine', 'Social Sciences'],
        website: 'https://www.manchester.ac.uk',
        ucas_code: 'M20'
    },
    {
        id: 'bristol',
        name: 'University of Bristol',
        location: 'Bristol',
        region: 'South West England',
        established: 1876,
        ranking_guardian: 14,
        ranking_complete_guide: 14,
        ranking_times: 14,
        acceptance_rate: 19.2,
        student_satisfaction_teaching: 86.1,
        student_satisfaction_feedback: 73.8,
        student_staff_ratio: 13.5,
        entry_tariff: 176,
        graduate_prospects: 90,
        tuition_fees_uk: 9250,
        tuition_fees_international: 29700,
        accommodation_cost: 7200,
        total_students: 28000,
        international_students_percentage: 28,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['research-excellence', 'graduate-employment', 'beautiful-city', 'strong-alumni'],
        popular_subjects: ['Engineering', 'Medicine', 'Law', 'Economics', 'Psychology', 'Geography'],
        website: 'https://www.bristol.ac.uk',
        ucas_code: 'B78'
    },
    {
        id: 'glasgow',
        name: 'University of Glasgow',
        location: 'Glasgow',
        region: 'Scotland',
        established: 1451,
        ranking_guardian: 15,
        ranking_complete_guide: 15,
        ranking_times: 15,
        acceptance_rate: 26.8,
        student_satisfaction_teaching: 85.7,
        student_satisfaction_feedback: 74.2,
        student_staff_ratio: 13.9,
        entry_tariff: 168,
        graduate_prospects: 86,
        tuition_fees_uk: 9250,
        tuition_fees_international: 25750,
        accommodation_cost: 6500,
        total_students: 33000,
        international_students_percentage: 35,
        research_quality: 'excellent',
        university_type: 'ancient',
        notable_strengths: ['historic-prestige', 'research-intensive', 'beautiful-campus', 'scottish-culture'],
        popular_subjects: ['Medicine', 'Engineering', 'Arts', 'Law', 'Business', 'Sciences'],
        website: 'https://www.gla.ac.uk',
        ucas_code: 'G28'
    },
    {
        id: 'southampton',
        name: 'University of Southampton',
        location: 'Southampton',
        region: 'South East England',
        established: 1862,
        ranking_guardian: 16,
        ranking_complete_guide: 16,
        ranking_times: 16,
        acceptance_rate: 31.5,
        student_satisfaction_teaching: 84.9,
        student_satisfaction_feedback: 71.8,
        student_staff_ratio: 14.8,
        entry_tariff: 158,
        graduate_prospects: 88,
        tuition_fees_uk: 9250,
        tuition_fees_international: 27400,
        accommodation_cost: 6900,
        total_students: 24000,
        international_students_percentage: 38,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['engineering-excellence', 'maritime-heritage', 'research-intensive', 'industry-partnerships'],
        popular_subjects: ['Engineering', 'Computer Science', 'Medicine', 'Business', 'Psychology'],
        website: 'https://www.southampton.ac.uk',
        ucas_code: 'S27'
    },
    {
        id: 'birmingham',
        name: 'University of Birmingham',
        location: 'Birmingham',
        region: 'West Midlands',
        established: 1900,
        ranking_guardian: 17,
        ranking_complete_guide: 17,
        ranking_times: 17,
        acceptance_rate: 29.3,
        student_satisfaction_teaching: 85.3,
        student_satisfaction_feedback: 72.5,
        student_staff_ratio: 14.6,
        entry_tariff: 164,
        graduate_prospects: 87,
        tuition_fees_uk: 9250,
        tuition_fees_international: 26040,
        accommodation_cost: 6400,
        total_students: 38000,
        international_students_percentage: 32,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['research-excellence', 'diverse-student-body', 'central-location', 'strong-alumni'],
        popular_subjects: ['Business', 'Engineering', 'Medicine', 'Law', 'Social Sciences'],
        website: 'https://www.birmingham.ac.uk',
        ucas_code: 'B32'
    },
    {
        id: 'leeds',
        name: 'University of Leeds',
        location: 'Leeds',
        region: 'Yorkshire and the Humber',
        established: 1904,
        ranking_guardian: 18,
        ranking_complete_guide: 18,
        ranking_times: 18,
        acceptance_rate: 32.1,
        student_satisfaction_teaching: 84.7,
        student_satisfaction_feedback: 71.2,
        student_staff_ratio: 15.1,
        entry_tariff: 161,
        graduate_prospects: 86,
        tuition_fees_uk: 9250,
        tuition_fees_international: 25500,
        accommodation_cost: 6200,
        total_students: 38500,
        international_students_percentage: 29,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['large-student-body', 'research-intensive', 'vibrant-city', 'industry-connections'],
        popular_subjects: ['Business', 'Engineering', 'Medicine', 'Arts', 'Social Sciences'],
        website: 'https://www.leeds.ac.uk',
        ucas_code: 'L23'
    },
    {
        id: 'nottingham',
        name: 'University of Nottingham',
        location: 'Nottingham',
        region: 'East Midlands',
        established: 1881,
        ranking_guardian: 19,
        ranking_complete_guide: 19,
        ranking_times: 19,
        acceptance_rate: 30.8,
        student_satisfaction_teaching: 85.1,
        student_satisfaction_feedback: 72.9,
        student_staff_ratio: 14.3,
        entry_tariff: 159,
        graduate_prospects: 87,
        tuition_fees_uk: 9250,
        tuition_fees_international: 26500,
        accommodation_cost: 6100,
        total_students: 35000,
        international_students_percentage: 31,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['beautiful-campus', 'research-excellence', 'international-campuses', 'student-experience'],
        popular_subjects: ['Medicine', 'Engineering', 'Business', 'Law', 'Psychology'],
        website: 'https://www.nottingham.ac.uk',
        ucas_code: 'N84'
    },
    {
        id: 'sheffield',
        name: 'University of Sheffield',
        location: 'Sheffield',
        region: 'Yorkshire and the Humber',
        established: 1905,
        ranking_guardian: 20,
        ranking_complete_guide: 20,
        ranking_times: 20,
        acceptance_rate: 33.2,
        student_satisfaction_teaching: 86.4,
        student_satisfaction_feedback: 74.1,
        student_staff_ratio: 14.7,
        entry_tariff: 157,
        graduate_prospects: 85,
        tuition_fees_uk: 9250,
        tuition_fees_international: 25670,
        accommodation_cost: 5900,
        total_students: 31000,
        international_students_percentage: 27,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['engineering-excellence', 'student-satisfaction', 'research-intensive', 'affordable-living'],
        popular_subjects: ['Engineering', 'Medicine', 'Architecture', 'Journalism', 'Psychology'],
        website: 'https://www.sheffield.ac.uk',
        ucas_code: 'S18'
    },

    // PLATE GLASS UNIVERSITIES (1960s)
    {
        id: 'york',
        name: 'University of York',
        location: 'York',
        region: 'Yorkshire and the Humber',
        established: 1963,
        ranking_guardian: 21,
        ranking_complete_guide: 21,
        ranking_times: 21,
        acceptance_rate: 28.9,
        student_satisfaction_teaching: 87.2,
        student_satisfaction_feedback: 75.3,
        student_staff_ratio: 13.8,
        entry_tariff: 165,
        graduate_prospects: 88,
        tuition_fees_uk: 9250,
        tuition_fees_international: 26040,
        accommodation_cost: 6800,
        total_students: 20000,
        international_students_percentage: 25,
        research_quality: 'excellent',
        university_type: 'plate_glass',
        notable_strengths: ['research-excellence', 'beautiful-campus', 'historic-city', 'student-satisfaction'],
        popular_subjects: ['Psychology', 'Computer Science', 'Economics', 'Politics', 'English'],
        website: 'https://www.york.ac.uk',
        ucas_code: 'Y50'
    },
    {
        id: 'lancaster',
        name: 'Lancaster University',
        location: 'Lancaster',
        region: 'North West England',
        established: 1964,
        ranking_guardian: 22,
        ranking_complete_guide: 22,
        ranking_times: 22,
        acceptance_rate: 27.6,
        student_satisfaction_teaching: 86.8,
        student_satisfaction_feedback: 74.8,
        student_staff_ratio: 13.2,
        entry_tariff: 163,
        graduate_prospects: 89,
        tuition_fees_uk: 9250,
        tuition_fees_international: 26550,
        accommodation_cost: 6300,
        total_students: 15000,
        international_students_percentage: 35,
        research_quality: 'excellent',
        university_type: 'plate_glass',
        notable_strengths: ['business-school', 'research-excellence', 'campus-university', 'student-experience'],
        popular_subjects: ['Business', 'Management', 'Psychology', 'Computer Science', 'Economics'],
        website: 'https://www.lancaster.ac.uk',
        ucas_code: 'L14'
    },
    {
        id: 'sussex',
        name: 'University of Sussex',
        location: 'Brighton',
        region: 'South East England',
        established: 1961,
        ranking_guardian: 23,
        ranking_complete_guide: 23,
        ranking_times: 23,
        acceptance_rate: 34.7,
        student_satisfaction_teaching: 85.9,
        student_satisfaction_feedback: 73.2,
        student_staff_ratio: 15.4,
        entry_tariff: 152,
        graduate_prospects: 84,
        tuition_fees_uk: 9250,
        tuition_fees_international: 25200,
        accommodation_cost: 7800,
        total_students: 19000,
        international_students_percentage: 38,
        research_quality: 'excellent',
        university_type: 'plate_glass',
        notable_strengths: ['research-excellence', 'coastal-location', 'liberal-arts', 'international-focus'],
        popular_subjects: ['International Relations', 'Psychology', 'Business', 'Media Studies', 'English'],
        website: 'https://www.sussex.ac.uk',
        ucas_code: 'S90'
    },
    {
        id: 'east-anglia',
        name: 'University of East Anglia',
        location: 'Norwich',
        region: 'East of England',
        established: 1963,
        ranking_guardian: 24,
        ranking_complete_guide: 24,
        ranking_times: 24,
        acceptance_rate: 36.2,
        student_satisfaction_teaching: 86.7,
        student_satisfaction_feedback: 74.6,
        student_staff_ratio: 14.9,
        entry_tariff: 148,
        graduate_prospects: 83,
        tuition_fees_uk: 9250,
        tuition_fees_international: 24500,
        accommodation_cost: 6400,
        total_students: 17000,
        international_students_percentage: 32,
        research_quality: 'excellent',
        university_type: 'plate_glass',
        notable_strengths: ['creative-writing', 'environmental-sciences', 'campus-university', 'student-satisfaction'],
        popular_subjects: ['Creative Writing', 'Environmental Sciences', 'Medicine', 'Psychology', 'Business'],
        website: 'https://www.uea.ac.uk',
        ucas_code: 'E14'
    },
    {
        id: 'essex',
        name: 'University of Essex',
        location: 'Colchester',
        region: 'East of England',
        established: 1964,
        ranking_guardian: 25,
        ranking_complete_guide: 25,
        ranking_times: 25,
        acceptance_rate: 38.5,
        student_satisfaction_teaching: 85.4,
        student_satisfaction_feedback: 72.8,
        student_staff_ratio: 16.2,
        entry_tariff: 145,
        graduate_prospects: 82,
        tuition_fees_uk: 9250,
        tuition_fees_international: 23200,
        accommodation_cost: 6100,
        total_students: 16500,
        international_students_percentage: 41,
        research_quality: 'excellent',
        university_type: 'plate_glass',
        notable_strengths: ['social-sciences', 'research-excellence', 'diverse-community', 'political-activism'],
        popular_subjects: ['Politics', 'Economics', 'Psychology', 'Sociology', 'Computer Science'],
        website: 'https://www.essex.ac.uk',
        ucas_code: 'E56'
    },

    // POST-1992 UNIVERSITIES (Former Polytechnics)
    {
        id: 'coventry',
        name: 'Coventry University',
        location: 'Coventry',
        region: 'West Midlands',
        established: 1992,
        ranking_guardian: 26,
        ranking_complete_guide: 26,
        ranking_times: 26,
        acceptance_rate: 42.3,
        student_satisfaction_teaching: 87.8,
        student_satisfaction_feedback: 76.2,
        student_staff_ratio: 17.1,
        entry_tariff: 138,
        graduate_prospects: 85,
        tuition_fees_uk: 9250,
        tuition_fees_international: 19850,
        accommodation_cost: 5800,
        total_students: 38000,
        international_students_percentage: 35,
        research_quality: 'good',
        university_type: 'post_1992',
        notable_strengths: ['student-satisfaction', 'industry-links', 'modern-facilities', 'practical-learning'],
        popular_subjects: ['Business', 'Engineering', 'Design', 'Health Sciences', 'Computing'],
        website: 'https://www.coventry.ac.uk',
        ucas_code: 'C85'
    },
    {
        id: 'northumbria',
        name: 'Northumbria University',
        location: 'Newcastle',
        region: 'North East England',
        established: 1992,
        ranking_guardian: 27,
        ranking_complete_guide: 27,
        ranking_times: 27,
        acceptance_rate: 44.1,
        student_satisfaction_teaching: 86.9,
        student_satisfaction_feedback: 75.4,
        student_staff_ratio: 16.8,
        entry_tariff: 142,
        graduate_prospects: 84,
        tuition_fees_uk: 9250,
        tuition_fees_international: 20500,
        accommodation_cost: 5600,
        total_students: 35000,
        international_students_percentage: 28,
        research_quality: 'good',
        university_type: 'post_1992',
        notable_strengths: ['student-experience', 'city-campus', 'industry-partnerships', 'graduate-employment'],
        popular_subjects: ['Business', 'Law', 'Engineering', 'Health Sciences', 'Design'],
        website: 'https://www.northumbria.ac.uk',
        ucas_code: 'N77'
    },
    {
        id: 'bournemouth',
        name: 'Bournemouth University',
        location: 'Bournemouth',
        region: 'South West England',
        established: 1992,
        ranking_guardian: 28,
        ranking_complete_guide: 28,
        ranking_times: 28,
        acceptance_rate: 46.7,
        student_satisfaction_teaching: 86.2,
        student_satisfaction_feedback: 74.9,
        student_staff_ratio: 17.5,
        entry_tariff: 135,
        graduate_prospects: 83,
        tuition_fees_uk: 9250,
        tuition_fees_international: 18800,
        accommodation_cost: 6700,
        total_students: 19000,
        international_students_percentage: 22,
        research_quality: 'good',
        university_type: 'post_1992',
        notable_strengths: ['media-production', 'coastal-location', 'industry-links', 'practical-courses'],
        popular_subjects: ['Media Production', 'Business', 'Tourism', 'Health Sciences', 'Computing'],
        website: 'https://www.bournemouth.ac.uk',
        ucas_code: 'B50'
    },
    {
        id: 'hertfordshire',
        name: 'University of Hertfordshire',
        location: 'Hatfield',
        region: 'East of England',
        established: 1992,
        ranking_guardian: 29,
        ranking_complete_guide: 29,
        ranking_times: 29,
        acceptance_rate: 48.2,
        student_satisfaction_teaching: 85.7,
        student_satisfaction_feedback: 73.6,
        student_staff_ratio: 18.1,
        entry_tariff: 132,
        graduate_prospects: 82,
        tuition_fees_uk: 9250,
        tuition_fees_international: 17500,
        accommodation_cost: 6200,
        total_students: 27000,
        international_students_percentage: 26,
        research_quality: 'good',
        university_type: 'post_1992',
        notable_strengths: ['business-school', 'modern-facilities', 'london-proximity', 'industry-partnerships'],
        popular_subjects: ['Business', 'Engineering', 'Health Sciences', 'Computing', 'Creative Arts'],
        website: 'https://www.herts.ac.uk',
        ucas_code: 'H36'
    },

    // SPECIALIST INSTITUTIONS
    {
        id: 'royal-college-art',
        name: 'Royal College of Art',
        location: 'London',
        region: 'London',
        established: 1837,
        ranking_guardian: 30,
        ranking_complete_guide: 30,
        ranking_times: 30,
        acceptance_rate: 15.2,
        student_satisfaction_teaching: 89.4,
        student_satisfaction_feedback: 78.9,
        student_staff_ratio: 8.5,
        entry_tariff: 180,
        graduate_prospects: 91,
        tuition_fees_uk: 9250,
        tuition_fees_international: 32500,
        accommodation_cost: 11000,
        total_students: 2500,
        international_students_percentage: 65,
        research_quality: 'world_leading',
        university_type: 'specialist',
        notable_strengths: ['art-design-excellence', 'world-renowned', 'industry-connections', 'innovation'],
        popular_subjects: ['Fine Art', 'Design', 'Architecture', 'Fashion', 'Digital Media'],
        website: 'https://www.rca.ac.uk',
        ucas_code: 'R72'
    },
    {
        id: 'london-business-school',
        name: 'London Business School',
        location: 'London',
        region: 'London',
        established: 1964,
        ranking_guardian: 31,
        ranking_complete_guide: 31,
        ranking_times: 31,
        acceptance_rate: 12.8,
        student_satisfaction_teaching: 91.2,
        student_satisfaction_feedback: 82.1,
        student_staff_ratio: 6.2,
        entry_tariff: 190,
        graduate_prospects: 95,
        tuition_fees_uk: 9250,
        tuition_fees_international: 55000,
        accommodation_cost: 12000,
        total_students: 2000,
        international_students_percentage: 85,
        research_quality: 'world_leading',
        university_type: 'specialist',
        notable_strengths: ['business-excellence', 'global-network', 'london-location', 'elite-programs'],
        popular_subjects: ['MBA', 'Finance', 'Management', 'Entrepreneurship', 'Strategy'],
        website: 'https://www.london.edu',
        ucas_code: 'L72'
    },
    {
        id: 'cranfield',
        name: 'Cranfield University',
        location: 'Cranfield',
        region: 'East of England',
        established: 1969,
        ranking_guardian: 32,
        ranking_complete_guide: 32,
        ranking_times: 32,
        acceptance_rate: 22.4,
        student_satisfaction_teaching: 88.7,
        student_satisfaction_feedback: 77.3,
        student_staff_ratio: 9.8,
        entry_tariff: 175,
        graduate_prospects: 93,
        tuition_fees_uk: 9250,
        tuition_fees_international: 38500,
        accommodation_cost: 7200,
        total_students: 5000,
        international_students_percentage: 55,
        research_quality: 'excellent',
        university_type: 'specialist',
        notable_strengths: ['aerospace-engineering', 'business-school', 'research-excellence', 'industry-links'],
        popular_subjects: ['Aerospace Engineering', 'Business', 'Manufacturing', 'Defence', 'Technology'],
        website: 'https://www.cranfield.ac.uk',
        ucas_code: 'C85'
    },

    // ADDITIONAL QUALITY UNIVERSITIES
    {
        id: 'reading',
        name: 'University of Reading',
        location: 'Reading',
        region: 'South East England',
        established: 1892,
        ranking_guardian: 33,
        ranking_complete_guide: 33,
        ranking_times: 33,
        acceptance_rate: 35.8,
        student_satisfaction_teaching: 85.8,
        student_satisfaction_feedback: 73.4,
        student_staff_ratio: 15.6,
        entry_tariff: 154,
        graduate_prospects: 85,
        tuition_fees_uk: 9250,
        tuition_fees_international: 24500,
        accommodation_cost: 6800,
        total_students: 22000,
        international_students_percentage: 30,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['agriculture-excellence', 'business-school', 'research-intensive', 'london-proximity'],
        popular_subjects: ['Agriculture', 'Business', 'Psychology', 'Archaeology', 'Food Science'],
        website: 'https://www.reading.ac.uk',
        ucas_code: 'R12'
    },
    {
        id: 'leicester',
        name: 'University of Leicester',
        location: 'Leicester',
        region: 'East Midlands',
        established: 1921,
        ranking_guardian: 34,
        ranking_complete_guide: 34,
        ranking_times: 34,
        acceptance_rate: 37.2,
        student_satisfaction_teaching: 86.1,
        student_satisfaction_feedback: 74.1,
        student_staff_ratio: 14.8,
        entry_tariff: 151,
        graduate_prospects: 84,
        tuition_fees_uk: 9250,
        tuition_fees_international: 23700,
        accommodation_cost: 5900,
        total_students: 24000,
        international_students_percentage: 28,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['space-research', 'archaeology', 'medical-school', 'diverse-community'],
        popular_subjects: ['Medicine', 'Archaeology', 'Space Science', 'Law', 'Psychology'],
        website: 'https://www.le.ac.uk',
        ucas_code: 'L34'
    },
    {
        id: 'surrey',
        name: 'University of Surrey',
        location: 'Guildford',
        region: 'South East England',
        established: 1966,
        ranking_guardian: 35,
        ranking_complete_guide: 35,
        ranking_times: 35,
        acceptance_rate: 33.9,
        student_satisfaction_teaching: 87.3,
        student_satisfaction_feedback: 75.8,
        student_staff_ratio: 14.2,
        entry_tariff: 156,
        graduate_prospects: 88,
        tuition_fees_uk: 9250,
        tuition_fees_international: 26500,
        accommodation_cost: 7400,
        total_students: 17000,
        international_students_percentage: 35,
        research_quality: 'excellent',
        university_type: 'plate_glass',
        notable_strengths: ['graduate-employment', 'industry-placements', 'research-excellence', 'london-proximity'],
        popular_subjects: ['Engineering', 'Business', 'Hospitality', 'Psychology', 'Computer Science'],
        website: 'https://www.surrey.ac.uk',
        ucas_code: 'S90'
    },

    // ADDITIONAL RUSSELL GROUP & TOP UNIVERSITIES
    {
        id: 'cardiff',
        name: 'Cardiff University',
        location: 'Cardiff',
        region: 'Wales',
        established: 1883,
        ranking_guardian: 36,
        ranking_complete_guide: 36,
        ranking_times: 36,
        acceptance_rate: 34.2,
        student_satisfaction_teaching: 85.9,
        student_satisfaction_feedback: 73.7,
        student_staff_ratio: 15.3,
        entry_tariff: 153,
        graduate_prospects: 86,
        tuition_fees_uk: 9000,
        tuition_fees_international: 25450,
        accommodation_cost: 6200,
        total_students: 32000,
        international_students_percentage: 26,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['journalism-school', 'research-excellence', 'welsh-capital', 'diverse-programs'],
        popular_subjects: ['Journalism', 'Medicine', 'Business', 'Psychology', 'Engineering'],
        website: 'https://www.cardiff.ac.uk',
        ucas_code: 'C15'
    },
    {
        id: 'queen-mary',
        name: 'Queen Mary University of London',
        location: 'London',
        region: 'London',
        established: 1887,
        ranking_guardian: 37,
        ranking_complete_guide: 37,
        ranking_times: 37,
        acceptance_rate: 39.8,
        student_satisfaction_teaching: 84.6,
        student_satisfaction_feedback: 71.9,
        student_staff_ratio: 16.4,
        entry_tariff: 149,
        graduate_prospects: 85,
        tuition_fees_uk: 9250,
        tuition_fees_international: 26750,
        accommodation_cost: 9800,
        total_students: 26000,
        international_students_percentage: 47,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['medical-school', 'london-location', 'research-intensive', 'diverse-community'],
        popular_subjects: ['Medicine', 'Dentistry', 'Law', 'Engineering', 'Computer Science'],
        website: 'https://www.qmul.ac.uk',
        ucas_code: 'Q50'
    },
    {
        id: 'newcastle',
        name: 'Newcastle University',
        location: 'Newcastle',
        region: 'North East England',
        established: 1834,
        ranking_guardian: 38,
        ranking_complete_guide: 38,
        ranking_times: 38,
        acceptance_rate: 36.7,
        student_satisfaction_teaching: 86.2,
        student_satisfaction_feedback: 74.3,
        student_staff_ratio: 15.8,
        entry_tariff: 150,
        graduate_prospects: 84,
        tuition_fees_uk: 9250,
        tuition_fees_international: 25200,
        accommodation_cost: 5800,
        total_students: 29000,
        international_students_percentage: 24,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['research-excellence', 'vibrant-city', 'student-life', 'affordable-living'],
        popular_subjects: ['Medicine', 'Engineering', 'Business', 'Architecture', 'Psychology'],
        website: 'https://www.ncl.ac.uk',
        ucas_code: 'N21'
    },
    {
        id: 'liverpool',
        name: 'University of Liverpool',
        location: 'Liverpool',
        region: 'North West England',
        established: 1881,
        ranking_guardian: 39,
        ranking_complete_guide: 39,
        ranking_times: 39,
        acceptance_rate: 38.4,
        student_satisfaction_teaching: 85.1,
        student_satisfaction_feedback: 72.6,
        student_staff_ratio: 16.2,
        entry_tariff: 147,
        graduate_prospects: 83,
        tuition_fees_uk: 9250,
        tuition_fees_international: 25050,
        accommodation_cost: 6100,
        total_students: 33000,
        international_students_percentage: 29,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['research-excellence', 'cultural-city', 'historic-university', 'international-partnerships'],
        popular_subjects: ['Medicine', 'Veterinary Science', 'Engineering', 'Business', 'Psychology'],
        website: 'https://www.liverpool.ac.uk',
        ucas_code: 'L41'
    },
    {
        id: 'exeter',
        name: 'University of Exeter',
        location: 'Exeter',
        region: 'South West England',
        established: 1955,
        ranking_guardian: 40,
        ranking_complete_guide: 40,
        ranking_times: 40,
        acceptance_rate: 32.8,
        student_satisfaction_teaching: 86.8,
        student_satisfaction_feedback: 75.1,
        student_staff_ratio: 14.9,
        entry_tariff: 158,
        graduate_prospects: 87,
        tuition_fees_uk: 9250,
        tuition_fees_international: 27000,
        accommodation_cost: 6800,
        total_students: 25000,
        international_students_percentage: 22,
        research_quality: 'excellent',
        university_type: 'plate_glass',
        notable_strengths: ['business-school', 'beautiful-campus', 'student-satisfaction', 'research-excellence'],
        popular_subjects: ['Business', 'Psychology', 'Sport Science', 'Medicine', 'English'],
        website: 'https://www.exeter.ac.uk',
        ucas_code: 'E84'
    },

    // STRONG POST-1992 & MODERN UNIVERSITIES
    {
        id: 'plymouth',
        name: 'University of Plymouth',
        location: 'Plymouth',
        region: 'South West England',
        established: 1992,
        ranking_guardian: 41,
        ranking_complete_guide: 41,
        ranking_times: 41,
        acceptance_rate: 45.3,
        student_satisfaction_teaching: 85.4,
        student_satisfaction_feedback: 73.8,
        student_staff_ratio: 17.2,
        entry_tariff: 134,
        graduate_prospects: 82,
        tuition_fees_uk: 9250,
        tuition_fees_international: 16500,
        accommodation_cost: 6400,
        total_students: 23000,
        international_students_percentage: 18,
        research_quality: 'good',
        university_type: 'post_1992',
        notable_strengths: ['marine-sciences', 'coastal-location', 'practical-learning', 'industry-links'],
        popular_subjects: ['Marine Biology', 'Business', 'Health Sciences', 'Engineering', 'Art'],
        website: 'https://www.plymouth.ac.uk',
        ucas_code: 'P60'
    },
    {
        id: 'portsmouth',
        name: 'University of Portsmouth',
        location: 'Portsmouth',
        region: 'South East England',
        established: 1992,
        ranking_guardian: 42,
        ranking_complete_guide: 42,
        ranking_times: 42,
        acceptance_rate: 47.1,
        student_satisfaction_teaching: 86.7,
        student_satisfaction_feedback: 75.2,
        student_staff_ratio: 17.8,
        entry_tariff: 131,
        graduate_prospects: 81,
        tuition_fees_uk: 9250,
        tuition_fees_international: 17900,
        accommodation_cost: 6600,
        total_students: 28000,
        international_students_percentage: 20,
        research_quality: 'good',
        university_type: 'post_1992',
        notable_strengths: ['student-satisfaction', 'coastal-city', 'modern-facilities', 'practical-courses'],
        popular_subjects: ['Business', 'Engineering', 'Creative Arts', 'Health Sciences', 'Computing'],
        website: 'https://www.port.ac.uk',
        ucas_code: 'P80'
    },
    {
        id: 'brighton',
        name: 'University of Brighton',
        location: 'Brighton',
        region: 'South East England',
        established: 1992,
        ranking_guardian: 43,
        ranking_complete_guide: 43,
        ranking_times: 43,
        acceptance_rate: 49.2,
        student_satisfaction_teaching: 85.9,
        student_satisfaction_feedback: 74.1,
        student_staff_ratio: 18.3,
        entry_tariff: 128,
        graduate_prospects: 80,
        tuition_fees_uk: 9250,
        tuition_fees_international: 15900,
        accommodation_cost: 7200,
        total_students: 21000,
        international_students_percentage: 16,
        research_quality: 'good',
        university_type: 'post_1992',
        notable_strengths: ['art-design', 'coastal-location', 'creative-industries', 'student-life'],
        popular_subjects: ['Art & Design', 'Architecture', 'Business', 'Health Sciences', 'Media'],
        website: 'https://www.brighton.ac.uk',
        ucas_code: 'B72'
    },
    {
        id: 'nottingham-trent',
        name: 'Nottingham Trent University',
        location: 'Nottingham',
        region: 'East Midlands',
        established: 1992,
        ranking_guardian: 44,
        ranking_complete_guide: 44,
        ranking_times: 44,
        acceptance_rate: 51.6,
        student_satisfaction_teaching: 87.1,
        student_satisfaction_feedback: 76.3,
        student_staff_ratio: 18.9,
        entry_tariff: 125,
        graduate_prospects: 79,
        tuition_fees_uk: 9250,
        tuition_fees_international: 16500,
        accommodation_cost: 5700,
        total_students: 33000,
        international_students_percentage: 14,
        research_quality: 'good',
        university_type: 'post_1992',
        notable_strengths: ['student-satisfaction', 'modern-facilities', 'industry-partnerships', 'vibrant-campus'],
        popular_subjects: ['Business', 'Law', 'Art & Design', 'Health Sciences', 'Media'],
        website: 'https://www.ntu.ac.uk',
        ucas_code: 'N84'
    },

    // SPECIALIST & UNIQUE INSTITUTIONS
    {
        id: 'goldsmiths',
        name: 'Goldsmiths, University of London',
        location: 'London',
        region: 'London',
        established: 1891,
        ranking_guardian: 45,
        ranking_complete_guide: 45,
        ranking_times: 45,
        acceptance_rate: 43.7,
        student_satisfaction_teaching: 84.2,
        student_satisfaction_feedback: 71.8,
        student_staff_ratio: 16.9,
        entry_tariff: 140,
        graduate_prospects: 78,
        tuition_fees_uk: 9250,
        tuition_fees_international: 21180,
        accommodation_cost: 9500,
        total_students: 10000,
        international_students_percentage: 52,
        research_quality: 'excellent',
        university_type: 'specialist',
        notable_strengths: ['creative-arts', 'media-studies', 'innovative-programs', 'london-location'],
        popular_subjects: ['Fine Art', 'Media Studies', 'Psychology', 'Sociology', 'Music'],
        website: 'https://www.gold.ac.uk',
        ucas_code: 'G56'
    },
    {
        id: 'royal-holloway',
        name: 'Royal Holloway, University of London',
        location: 'Egham',
        region: 'South East England',
        established: 1886,
        ranking_guardian: 46,
        ranking_complete_guide: 46,
        ranking_times: 46,
        acceptance_rate: 41.3,
        student_satisfaction_teaching: 85.6,
        student_satisfaction_feedback: 73.9,
        student_staff_ratio: 15.7,
        entry_tariff: 144,
        graduate_prospects: 82,
        tuition_fees_uk: 9250,
        tuition_fees_international: 23800,
        accommodation_cost: 7100,
        total_students: 11000,
        international_students_percentage: 38,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['beautiful-campus', 'research-excellence', 'small-class-sizes', 'london-proximity'],
        popular_subjects: ['English', 'Psychology', 'Computer Science', 'Economics', 'Drama'],
        website: 'https://www.royalholloway.ac.uk',
        ucas_code: 'R72'
    },
    {
        id: 'brunel',
        name: 'Brunel University London',
        location: 'Uxbridge',
        region: 'London',
        established: 1966,
        ranking_guardian: 47,
        ranking_complete_guide: 47,
        ranking_times: 47,
        acceptance_rate: 44.8,
        student_satisfaction_teaching: 84.7,
        student_satisfaction_feedback: 72.4,
        student_staff_ratio: 17.1,
        entry_tariff: 136,
        graduate_prospects: 83,
        tuition_fees_uk: 9250,
        tuition_fees_international: 20000,
        accommodation_cost: 8200,
        total_students: 16000,
        international_students_percentage: 45,
        research_quality: 'good',
        university_type: 'plate_glass',
        notable_strengths: ['engineering-focus', 'industry-placements', 'modern-campus', 'london-access'],
        popular_subjects: ['Engineering', 'Business', 'Computer Science', 'Design', 'Health Sciences'],
        website: 'https://www.brunel.ac.uk',
        ucas_code: 'B94'
    },
    {
        id: 'city-london',
        name: 'City, University of London',
        location: 'London',
        region: 'London',
        established: 1894,
        ranking_guardian: 48,
        ranking_complete_guide: 48,
        ranking_times: 48,
        acceptance_rate: 42.5,
        student_satisfaction_teaching: 83.9,
        student_satisfaction_feedback: 70.6,
        student_staff_ratio: 16.3,
        entry_tariff: 141,
        graduate_prospects: 85,
        tuition_fees_uk: 9250,
        tuition_fees_international: 22500,
        accommodation_cost: 10200,
        total_students: 20000,
        international_students_percentage: 55,
        research_quality: 'good',
        university_type: 'specialist',
        notable_strengths: ['business-school', 'london-location', 'professional-focus', 'industry-connections'],
        popular_subjects: ['Business', 'Law', 'Engineering', 'Journalism', 'Health Sciences'],
        website: 'https://www.city.ac.uk',
        ucas_code: 'C30'
    },
    {
        id: 'keele',
        name: 'Keele University',
        location: 'Keele',
        region: 'West Midlands',
        established: 1962,
        ranking_guardian: 49,
        ranking_complete_guide: 49,
        ranking_times: 49,
        acceptance_rate: 46.9,
        student_satisfaction_teaching: 86.5,
        student_satisfaction_feedback: 75.7,
        student_staff_ratio: 16.8,
        entry_tariff: 133,
        graduate_prospects: 81,
        tuition_fees_uk: 9250,
        tuition_fees_international: 18000,
        accommodation_cost: 5900,
        total_students: 12000,
        international_students_percentage: 22,
        research_quality: 'good',
        university_type: 'plate_glass',
        notable_strengths: ['campus-university', 'student-satisfaction', 'medical-school', 'supportive-environment'],
        popular_subjects: ['Medicine', 'Psychology', 'Business', 'Natural Sciences', 'Education'],
        website: 'https://www.keele.ac.uk',
        ucas_code: 'K12'
    },
    {
        id: 'stirling',
        name: 'University of Stirling',
        location: 'Stirling',
        region: 'Scotland',
        established: 1967,
        ranking_guardian: 50,
        ranking_complete_guide: 50,
        ranking_times: 50,
        acceptance_rate: 48.3,
        student_satisfaction_teaching: 85.8,
        student_satisfaction_feedback: 74.5,
        student_staff_ratio: 17.4,
        entry_tariff: 130,
        graduate_prospects: 80,
        tuition_fees_uk: 9250,
        tuition_fees_international: 16400,
        accommodation_cost: 6000,
        total_students: 14000,
        international_students_percentage: 28,
        research_quality: 'good',
        university_type: 'plate_glass',
        notable_strengths: ['beautiful-campus', 'sports-excellence', 'student-experience', 'scottish-heritage'],
        popular_subjects: ['Sport Science', 'Business', 'Psychology', 'Education', 'Media'],
        website: 'https://www.stir.ac.uk',
        ucas_code: 'S84'
    },
    // Additional UK Universities (51-100)
    {
        id: 'aberdeen',
        name: 'University of Aberdeen',
        location: 'Aberdeen',
        region: 'Scotland',
        established: 1495,
        ranking_guardian: 35,
        ranking_complete_guide: 38,
        ranking_times: 32,
        acceptance_rate: 65.0,
        student_satisfaction_teaching: 84.2,
        student_satisfaction_feedback: 71.3,
        student_staff_ratio: 15.2,
        entry_tariff: 155,
        graduate_prospects: 82,
        tuition_fees_uk: 9250,
        tuition_fees_international: 24800,
        accommodation_cost: 6200,
        total_students: 17500,
        international_students_percentage: 35,
        research_quality: 'excellent',
        university_type: 'ancient',
        notable_strengths: ['medicine', 'oil-gas-engineering', 'research-excellence', 'historic-tradition'],
        popular_subjects: ['Medicine', 'Engineering', 'Law', 'Business', 'Natural Sciences'],
        website: 'https://www.abdn.ac.uk',
        ucas_code: 'A20'
    },
    {
        id: 'dundee',
        name: 'University of Dundee',
        location: 'Dundee',
        region: 'Scotland',
        established: 1881,
        ranking_guardian: 32,
        ranking_complete_guide: 35,
        ranking_times: 29,
        acceptance_rate: 70.0,
        student_satisfaction_teaching: 86.1,
        student_satisfaction_feedback: 73.8,
        student_staff_ratio: 14.5,
        entry_tariff: 160,
        graduate_prospects: 85,
        tuition_fees_uk: 9250,
        tuition_fees_international: 25300,
        accommodation_cost: 5900,
        total_students: 18200,
        international_students_percentage: 28,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['life-sciences', 'medicine', 'art-design', 'student-satisfaction'],
        popular_subjects: ['Medicine', 'Life Sciences', 'Art & Design', 'Law', 'Engineering'],
        website: 'https://www.dundee.ac.uk',
        ucas_code: 'D65'
    },
    {
        id: 'strathclyde',
        name: 'University of Strathclyde',
        location: 'Glasgow',
        region: 'Scotland',
        established: 1796,
        ranking_guardian: 28,
        ranking_complete_guide: 31,
        ranking_times: 26,
        acceptance_rate: 68.0,
        student_satisfaction_teaching: 85.3,
        student_satisfaction_feedback: 72.1,
        student_staff_ratio: 15.8,
        entry_tariff: 165,
        graduate_prospects: 87,
        tuition_fees_uk: 9250,
        tuition_fees_international: 23750,
        accommodation_cost: 6400,
        total_students: 23000,
        international_students_percentage: 30,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['engineering', 'business', 'technology', 'industry-links'],
        popular_subjects: ['Engineering', 'Business', 'Computer Science', 'Pharmacy', 'Architecture'],
        website: 'https://www.strath.ac.uk',
        ucas_code: 'S78'
    },
    {
        id: 'heriot-watt',
        name: 'Heriot-Watt University',
        location: 'Edinburgh',
        region: 'Scotland',
        established: 1821,
        ranking_guardian: 42,
        ranking_complete_guide: 40,
        ranking_times: 38,
        acceptance_rate: 72.0,
        student_satisfaction_teaching: 83.7,
        student_satisfaction_feedback: 69.8,
        student_staff_ratio: 16.2,
        entry_tariff: 150,
        graduate_prospects: 84,
        tuition_fees_uk: 9250,
        tuition_fees_international: 22400,
        accommodation_cost: 6800,
        total_students: 12000,
        international_students_percentage: 45,
        research_quality: 'good',
        university_type: 'new',
        notable_strengths: ['engineering', 'technology', 'international-campuses', 'industry-focus'],
        popular_subjects: ['Engineering', 'Computer Science', 'Business', 'Mathematics', 'Actuarial Science'],
        website: 'https://www.hw.ac.uk',
        ucas_code: 'H36'
    },
    {
        id: 'robert-gordon',
        name: 'Robert Gordon University',
        location: 'Aberdeen',
        region: 'Scotland',
        established: 1992,
        ranking_guardian: 55,
        ranking_complete_guide: 52,
        ranking_times: 48,
        acceptance_rate: 78.0,
        student_satisfaction_teaching: 84.9,
        student_satisfaction_feedback: 71.2,
        student_staff_ratio: 17.1,
        entry_tariff: 140,
        graduate_prospects: 86,
        tuition_fees_uk: 9250,
        tuition_fees_international: 17410,
        accommodation_cost: 5600,
        total_students: 16500,
        international_students_percentage: 25,
        research_quality: 'good',
        university_type: 'post_1992',
        notable_strengths: ['employability', 'industry-links', 'practical-focus', 'modern-facilities'],
        popular_subjects: ['Engineering', 'Business', 'Health Sciences', 'Computing', 'Architecture'],
        website: 'https://www.rgu.ac.uk',
        ucas_code: 'R48'
    },
    {
        id: 'queen-margaret',
        name: 'Queen Margaret University',
        location: 'Edinburgh',
        region: 'Scotland',
        established: 1875,
        ranking_guardian: 68,
        ranking_complete_guide: 65,
        ranking_times: 62,
        acceptance_rate: 82.0,
        student_satisfaction_teaching: 83.1,
        student_satisfaction_feedback: 68.9,
        student_staff_ratio: 18.3,
        entry_tariff: 125,
        graduate_prospects: 79,
        tuition_fees_uk: 9250,
        tuition_fees_international: 16500,
        accommodation_cost: 6200,
        total_students: 5200,
        international_students_percentage: 20,
        research_quality: 'good',
        university_type: 'post_1992',
        notable_strengths: ['health-sciences', 'drama-performance', 'small-class-sizes', 'supportive-environment'],
        popular_subjects: ['Health Sciences', 'Drama', 'Business', 'Psychology', 'Media'],
        website: 'https://www.qmu.ac.uk',
        ucas_code: 'Q75'
    },
    {
        id: 'glasgow-caledonian',
        name: 'Glasgow Caledonian University',
        location: 'Glasgow',
        region: 'Scotland',
        established: 1993,
        ranking_guardian: 72,
        ranking_complete_guide: 68,
        ranking_times: 65,
        acceptance_rate: 85.0,
        student_satisfaction_teaching: 82.4,
        student_satisfaction_feedback: 67.5,
        student_staff_ratio: 19.2,
        entry_tariff: 130,
        graduate_prospects: 81,
        tuition_fees_uk: 9250,
        tuition_fees_international: 15500,
        accommodation_cost: 5800,
        total_students: 20000,
        international_students_percentage: 22,
        research_quality: 'good',
        university_type: 'post_1992',
        notable_strengths: ['health-sciences', 'social-innovation', 'diversity', 'community-focus'],
        popular_subjects: ['Health Sciences', 'Business', 'Engineering', 'Social Work', 'Computing'],
        website: 'https://www.gcu.ac.uk',
        ucas_code: 'G70'
    },
    {
        id: 'napier',
        name: 'Edinburgh Napier University',
        location: 'Edinburgh',
        region: 'Scotland',
        established: 1992,
        ranking_guardian: 75,
        ranking_complete_guide: 72,
        ranking_times: 68,
        acceptance_rate: 88.0,
        student_satisfaction_teaching: 81.7,
        student_satisfaction_feedback: 66.8,
        student_staff_ratio: 20.1,
        entry_tariff: 125,
        graduate_prospects: 78,
        tuition_fees_uk: 9250,
        tuition_fees_international: 16425,
        accommodation_cost: 6500,
        total_students: 19500,
        international_students_percentage: 18,
        research_quality: 'good',
        university_type: 'post_1992',
        notable_strengths: ['computing', 'business', 'creative-industries', 'practical-learning'],
        popular_subjects: ['Computing', 'Business', 'Engineering', 'Creative Arts', 'Health'],
        website: 'https://www.napier.ac.uk',
        ucas_code: 'E28'
    },
    {
        id: 'west-scotland',
        name: 'University of the West of Scotland',
        location: 'Paisley',
        region: 'Scotland',
        established: 2007,
        ranking_guardian: 85,
        ranking_complete_guide: 82,
        ranking_times: 78,
        acceptance_rate: 90.0,
        student_satisfaction_teaching: 80.2,
        student_satisfaction_feedback: 65.1,
        student_staff_ratio: 21.5,
        entry_tariff: 115,
        graduate_prospects: 75,
        tuition_fees_uk: 9250,
        tuition_fees_international: 15000,
        accommodation_cost: 5200,
        total_students: 17000,
        international_students_percentage: 15,
        research_quality: 'satisfactory',
        university_type: 'post_1992',
        notable_strengths: ['accessibility', 'community-engagement', 'practical-courses', 'affordable'],
        popular_subjects: ['Business', 'Health', 'Education', 'Computing', 'Creative Arts'],
        website: 'https://www.uws.ac.uk',
        ucas_code: 'U65'
    },
    // Additional English Universities (61-100)
    {
        id: 'hull',
        name: 'University of Hull',
        location: 'Hull',
        region: 'Yorkshire and the Humber',
        established: 1927,
        ranking_guardian: 58,
        ranking_complete_guide: 55,
        ranking_times: 52,
        acceptance_rate: 80.0,
        student_satisfaction_teaching: 83.5,
        student_satisfaction_feedback: 70.2,
        student_staff_ratio: 17.8,
        entry_tariff: 135,
        graduate_prospects: 79,
        tuition_fees_uk: 9250,
        tuition_fees_international: 19500,
        accommodation_cost: 5400,
        total_students: 16000,
        international_students_percentage: 18,
        research_quality: 'good',
        university_type: 'red_brick',
        notable_strengths: ['maritime-studies', 'politics', 'creative-writing', 'affordable'],
        popular_subjects: ['Business', 'Engineering', 'Politics', 'Creative Writing', 'Psychology'],
        website: 'https://www.hull.ac.uk',
        ucas_code: 'H72'
    },
    {
        id: 'swansea',
        name: 'Swansea University',
        location: 'Swansea',
        region: 'Wales',
        established: 1920,
        ranking_guardian: 31,
        ranking_complete_guide: 34,
        ranking_times: 28,
        acceptance_rate: 72.0,
        student_satisfaction_teaching: 85.8,
        student_satisfaction_feedback: 74.1,
        student_staff_ratio: 15.6,
        entry_tariff: 155,
        graduate_prospects: 83,
        tuition_fees_uk: 9250,
        tuition_fees_international: 22950,
        accommodation_cost: 6100,
        total_students: 21000,
        international_students_percentage: 25,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['engineering', 'medicine', 'beautiful-campus', 'research-excellence'],
        popular_subjects: ['Engineering', 'Medicine', 'Computer Science', 'Psychology', 'Business'],
        website: 'https://www.swansea.ac.uk',
        ucas_code: 'S93'
    },
    {
        id: 'bangor',
        name: 'Bangor University',
        location: 'Bangor',
        region: 'Wales',
        established: 1884,
        ranking_guardian: 62,
        ranking_complete_guide: 58,
        ranking_times: 55,
        acceptance_rate: 85.0,
        student_satisfaction_teaching: 84.3,
        student_satisfaction_feedback: 71.8,
        student_staff_ratio: 16.9,
        entry_tariff: 130,
        graduate_prospects: 77,
        tuition_fees_uk: 9250,
        tuition_fees_international: 18000,
        accommodation_cost: 5200,
        total_students: 11000,
        international_students_percentage: 20,
        research_quality: 'good',
        university_type: 'red_brick',
        notable_strengths: ['psychology', 'ocean-sciences', 'forestry', 'welsh-culture'],
        popular_subjects: ['Psychology', 'Ocean Sciences', 'Business', 'Education', 'Forestry'],
        website: 'https://www.bangor.ac.uk',
        ucas_code: 'B06'
    },
    {
        id: 'aberystwyth',
        name: 'Aberystwyth University',
        location: 'Aberystwyth',
        region: 'Wales',
        established: 1872,
        ranking_guardian: 45,
        ranking_complete_guide: 42,
        ranking_times: 39,
        acceptance_rate: 78.0,
        student_satisfaction_teaching: 86.2,
        student_satisfaction_feedback: 75.3,
        student_staff_ratio: 15.1,
        entry_tariff: 140,
        graduate_prospects: 81,
        tuition_fees_uk: 9250,
        tuition_fees_international: 18350,
        accommodation_cost: 5800,
        total_students: 8500,
        international_students_percentage: 22,
        research_quality: 'excellent',
        university_type: 'red_brick',
        notable_strengths: ['international-politics', 'agriculture', 'welsh-studies', 'coastal-location'],
        popular_subjects: ['International Politics', 'Agriculture', 'Computer Science', 'Geography', 'History'],
        website: 'https://www.aber.ac.uk',
        ucas_code: 'A40'
    },
    {
        id: 'chester',
        name: 'University of Chester',
        location: 'Chester',
        region: 'North West England',
        established: 1839,
        ranking_guardian: 78,
        ranking_complete_guide: 75,
        ranking_times: 72,
        acceptance_rate: 88.0,
        student_satisfaction_teaching: 82.1,
        student_satisfaction_feedback: 68.4,
        student_staff_ratio: 18.7,
        entry_tariff: 120,
        graduate_prospects: 76,
        tuition_fees_uk: 9250,
        tuition_fees_international: 14750,
        accommodation_cost: 5600,
        total_students: 19500,
        international_students_percentage: 12,
        research_quality: 'good',
        university_type: 'post_1992',
        notable_strengths: ['teacher-training', 'health-sciences', 'supportive-environment', 'historic-city'],
        popular_subjects: ['Education', 'Health Sciences', 'Business', 'Psychology', 'Sport Sciences'],
        website: 'https://www.chester.ac.uk',
        ucas_code: 'C58'
    },
    {
        id: 'central-lancashire',
        name: 'University of Central Lancashire',
        location: 'Preston',
        region: 'North West England',
        established: 1992,
        ranking_guardian: 82,
        ranking_complete_guide: 78,
        ranking_times: 75,
        acceptance_rate: 90.0,
        student_satisfaction_teaching: 81.3,
        student_satisfaction_feedback: 67.2,
        student_staff_ratio: 19.8,
        entry_tariff: 115,
        graduate_prospects: 74,
        tuition_fees_uk: 9250,
        tuition_fees_international: 15500,
        accommodation_cost: 5200,
        total_students: 38000,
        international_students_percentage: 15,
        research_quality: 'good',
        university_type: 'post_1992',
        notable_strengths: ['journalism', 'forensic-science', 'large-student-body', 'diverse-courses'],
        popular_subjects: ['Journalism', 'Forensic Science', 'Business', 'Engineering', 'Health'],
        website: 'https://www.uclan.ac.uk',
        ucas_code: 'C30'
    },
    {
        id: 'salford',
        name: 'University of Salford',
        location: 'Salford',
        region: 'North West England',
        established: 1967,
        ranking_guardian: 88,
        ranking_complete_guide: 85,
        ranking_times: 82,
        acceptance_rate: 92.0,
        student_satisfaction_teaching: 80.7,
        student_satisfaction_feedback: 65.8,
        student_staff_ratio: 20.5,
        entry_tariff: 110,
        graduate_prospects: 72,
        tuition_fees_uk: 9250,
        tuition_fees_international: 17040,
        accommodation_cost: 5800,
        total_students: 24000,
        international_students_percentage: 18,
        research_quality: 'good',
        university_type: 'new',
        notable_strengths: ['media-production', 'built-environment', 'industry-links', 'manchester-proximity'],
        popular_subjects: ['Media Production', 'Built Environment', 'Business', 'Health Sciences', 'Computing'],
        website: 'https://www.salford.ac.uk',
        ucas_code: 'S03'
    },
    {
        id: 'huddersfield',
        name: 'University of Huddersfield',
        location: 'Huddersfield',
        region: 'Yorkshire and the Humber',
        established: 1992,
        ranking_guardian: 65,
        ranking_complete_guide: 62,
        ranking_times: 58,
        acceptance_rate: 85.0,
        student_satisfaction_teaching: 83.9,
        student_satisfaction_feedback: 69.7,
        student_staff_ratio: 17.3,
        entry_tariff: 125,
        graduate_prospects: 78,
        tuition_fees_uk: 9250,
        tuition_fees_international: 17600,
        accommodation_cost: 5100,
        total_students: 20000,
        international_students_percentage: 25,
        research_quality: 'good',
        university_type: 'post_1992',
        notable_strengths: ['music-technology', 'textiles', 'employability', 'modern-facilities'],
        popular_subjects: ['Music Technology', 'Textiles', 'Business', 'Engineering', 'Health'],
        website: 'https://www.hud.ac.uk',
        ucas_code: 'H60'
    },
    {
        id: 'bradford',
        name: 'University of Bradford',
        location: 'Bradford',
        region: 'Yorkshire and the Humber',
        established: 1966,
        ranking_guardian: 92,
        ranking_complete_guide: 88,
        ranking_times: 85,
        acceptance_rate: 88.0,
        student_satisfaction_teaching: 81.1,
        student_satisfaction_feedback: 66.3,
        student_staff_ratio: 19.1,
        entry_tariff: 115,
        graduate_prospects: 73,
        tuition_fees_uk: 9250,
        tuition_fees_international: 20118,
        accommodation_cost: 5300,
        total_students: 14000,
        international_students_percentage: 35,
        research_quality: 'good',
        university_type: 'new',
        notable_strengths: ['pharmacy', 'optometry', 'peace-studies', 'diversity'],
        popular_subjects: ['Pharmacy', 'Optometry', 'Peace Studies', 'Business', 'Engineering'],
        website: 'https://www.bradford.ac.uk',
        ucas_code: 'B72'
    },
    {
        id: 'lincoln',
        name: 'University of Lincoln',
        location: 'Lincoln',
        region: 'East Midlands',
        established: 1992,
        ranking_guardian: 52,
        ranking_complete_guide: 48,
        ranking_times: 45,
        acceptance_rate: 82.0,
        student_satisfaction_teaching: 85.1,
        student_satisfaction_feedback: 72.6,
        student_staff_ratio: 16.4,
        entry_tariff: 135,
        graduate_prospects: 80,
        tuition_fees_uk: 9250,
        tuition_fees_international: 16200,
        accommodation_cost: 5700,
        total_students: 15500,
        international_students_percentage: 16,
        research_quality: 'good',
        university_type: 'post_1992',
        notable_strengths: ['animal-behaviour', 'journalism', 'modern-campus', 'student-satisfaction'],
        popular_subjects: ['Animal Behaviour', 'Journalism', 'Business', 'Psychology', 'Engineering'],
        website: 'https://www.lincoln.ac.uk',
        ucas_code: 'L46'
    }
];

// UK University Data Manager
export class UKUniversityDataManager {
    private cache: Map<string, EnhancedUniversity[]> = new Map();
    private lastFetch: number = 0;
    private cacheTimeout: number = 86400000; // 24 hours

    /**
     * Fetch UK universities and convert to enhanced format
     */
    async fetchUKUniversities(limit: number = 50): Promise<EnhancedUniversity[]> {
        const cacheKey = `uk-universities-${limit}`;
        
        // Check cache first
        if (this.cache.has(cacheKey) && (Date.now() - this.lastFetch) < this.cacheTimeout) {
            console.log('🇬🇧 Returning cached UK universities data');
            return this.cache.get(cacheKey)!;
        }

        try {
            console.log('🇬🇧 Fetching UK universities data');
            
            // Take the top universities by ranking (average of guardian and complete guide)
            const sortedUniversities = UK_UNIVERSITIES
                .map(uni => ({
                    ...uni,
                    average_ranking: (uni.ranking_guardian + uni.ranking_complete_guide) / 2
                }))
                .sort((a, b) => a.average_ranking - b.average_ranking)
                .slice(0, limit);

            const enhancedUniversities = sortedUniversities.map(uni => this.convertToEnhanced(uni));
            
            // Cache the results
            this.cache.set(cacheKey, enhancedUniversities);
            this.lastFetch = Date.now();
            
            console.log(`✅ Successfully processed ${enhancedUniversities.length} UK universities`);
            return enhancedUniversities;

        } catch (error) {
            console.error('❌ Error fetching UK universities:', error);
            // Return top 10 as fallback
            return UK_UNIVERSITIES.slice(0, 10).map(uni => this.convertToEnhanced(uni));
        }
    }

    /**
     * Convert UK university data to enhanced university format
     */
    private convertToEnhanced(ukUni: UKUniversityData): EnhancedUniversity {
        return {
            id: `uk-${ukUni.id}`,
            name: ukUni.name,
            country: 'United Kingdom',
            state: this.mapRegionToState(ukUni.region),
            city: ukUni.location,
            region: 'Europe',
            ranking: ukUni.ranking_guardian,
            global_ranking: this.estimateGlobalRanking(ukUni.ranking_guardian),
            national_ranking: ukUni.ranking_guardian,
            acceptance_rate: ukUni.acceptance_rate,
            avg_gpa: this.estimateGPAFromTariff(ukUni.entry_tariff),
            avg_sat: undefined, // Not applicable for UK
            avg_act: undefined, // Not applicable for UK
            strengths: ukUni.notable_strengths,
            programs: this.generateProgramScores(ukUni),
            requirements: {
                min_gpa: this.estimateMinGPA(ukUni.acceptance_rate),
                english_test: true,
                research_experience: this.getResearchRequirement(ukUni.university_type)
            },
            cost: ukUni.tuition_fees_international, // Use international fees for comparison
            living_cost: ukUni.accommodation_cost + 8000, // Accommodation + living expenses
            in_state_tuition: ukUni.tuition_fees_uk,
            out_of_state_tuition: ukUni.tuition_fees_international,
            scholarships: true,
            scholarship_percentage: this.estimateScholarshipAvailability(ukUni),
            median_debt: this.estimateMedianDebt(ukUni.tuition_fees_uk),
            graduate_earnings: this.estimateGraduateEarnings(ukUni.graduate_prospects),
            location_type: this.determineLocationType(ukUni.location),
            class_size: this.determineClassSize(ukUni.student_staff_ratio),
            research_opportunities: this.getResearchOpportunities(ukUni.research_quality),
            student_size: ukUni.total_students,
            ownership_type: 'public' as const, // Most UK universities are public
            carnegie_classification: undefined, // Not applicable for UK
            website_url: ukUni.website,
            data_source: 'hardcoded' as const,
            last_updated: new Date().toISOString()
        };
    }

    /**
     * Generate program scores based on university strengths and popular subjects
     */
    private generateProgramScores(ukUni: UKUniversityData): { [key: string]: number } {
        const programs: { [key: string]: number } = {};
        
        // Base score based on overall ranking
        const baseScore = Math.max(60, 100 - (ukUni.ranking_guardian * 2));
        
        // Map popular subjects to our program categories
        const subjectMapping: { [key: string]: string[] } = {
            'computer-science': ['Computer Science', 'Computing'],
            'engineering': ['Engineering'],
            'business': ['Business', 'Management'],
            'economics': ['Economics'],
            'law': ['Law'],
            'medicine': ['Medicine'],
            'psychology': ['Psychology'],
            'history': ['History'],
            'english-literature': ['English', 'English Literature'],
            'politics': ['Politics', 'Political Science'],
            'international-relations': ['International Relations'],
            'philosophy': ['Philosophy'],
            'mathematics': ['Mathematics', 'Maths'],
            'physics': ['Physics'],
            'chemistry': ['Chemistry'],
            'biology': ['Biology', 'Biological Sciences'],
            'architecture': ['Architecture'],
            'design': ['Design'],
            'media': ['Media', 'Communications'],
            'education': ['Education'],
            'geography': ['Geography']
        };

        // Score programs based on popular subjects
        for (const [program, subjects] of Object.entries(subjectMapping)) {
            if (ukUni.popular_subjects.some(subject => 
                subjects.some(mappedSubject => 
                    subject.toLowerCase().includes(mappedSubject.toLowerCase())
                )
            )) {
                programs[program] = Math.min(95, baseScore + 10);
            } else {
                programs[program] = baseScore;
            }
        }

        // Add bonuses for specific university types and strengths
        if (ukUni.notable_strengths.includes('research-excellence')) {
            programs['phd-programs'] = Math.min(95, baseScore + 15);
        }

        if (ukUni.university_type === 'specialist') {
            // LSE gets economics boost, Imperial gets STEM boost
            if (ukUni.id === 'lse') {
                programs['economics'] = 95;
                programs['political-science'] = 94;
                programs['international-relations'] = 93;
            } else if (ukUni.id === 'imperial') {
                programs['engineering'] = 95;
                programs['computer-science'] = 94;
                programs['medicine'] = 93;
            }
        }

        return programs;
    }

    /**
     * Helper functions for data conversion
     */
    private mapRegionToState(region: string): string {
        const regionMap: { [key: string]: string } = {
            'London': 'London',
            'South East England': 'South East',
            'South West England': 'South West',
            'North East England': 'North East',
            'North West England': 'North West',
            'West Midlands': 'West Midlands',
            'East Midlands': 'East Midlands',
            'East of England': 'East of England',
            'Yorkshire and the Humber': 'Yorkshire',
            'Scotland': 'Scotland',
            'Wales': 'Wales',
            'Northern Ireland': 'Northern Ireland'
        };
        return regionMap[region] || region;
    }

    private estimateGlobalRanking(ukRanking: number): number {
        // Rough conversion from UK ranking to global ranking
        if (ukRanking <= 5) return ukRanking;
        if (ukRanking <= 10) return ukRanking + 5;
        if (ukRanking <= 20) return ukRanking + 10;
        return ukRanking + 20;
    }

    private estimateGPAFromTariff(tariff: number): number {
        // Convert UCAS tariff points to approximate GPA equivalent
        if (tariff >= 200) return 3.9;
        if (tariff >= 180) return 3.7;
        if (tariff >= 160) return 3.5;
        if (tariff >= 140) return 3.3;
        return 3.0;
    }

    private estimateMinGPA(acceptanceRate: number): number {
        if (acceptanceRate < 15) return 3.8;
        if (acceptanceRate < 25) return 3.6;
        if (acceptanceRate < 35) return 3.4;
        return 3.2;
    }

    private getResearchRequirement(type: string): string {
        if (type === 'ancient' || type === 'specialist') return 'highly-preferred';
        if (type === 'red_brick' || type === 'plate_glass') return 'preferred';
        return 'optional';
    }

    private estimateScholarshipAvailability(ukUni: UKUniversityData): number {
        // UK universities generally have good scholarship availability
        if (ukUni.ranking_guardian <= 5) return 45;
        if (ukUni.ranking_guardian <= 10) return 40;
        if (ukUni.ranking_guardian <= 20) return 35;
        return 30;
    }

    private estimateMedianDebt(tuitionFees: number): number {
        // UK student debt calculation (rough estimate)
        return tuitionFees * 3 + 15000; // 3 years tuition + living costs
    }

    private estimateGraduateEarnings(prospects: number): number {
        // Convert graduate prospects percentage to approximate earnings
        return Math.round(prospects * 500 + 15000);
    }

    private determineLocationType(location: string): string {
        const majorCities = ['London', 'Birmingham', 'Manchester', 'Edinburgh', 'Glasgow', 'Leeds', 'Bristol'];
        if (majorCities.includes(location)) return 'urban';
        
        const universityCities = ['Oxford', 'Cambridge', 'Bath', 'Durham', 'St Andrews'];
        if (universityCities.includes(location)) return 'historic-town';
        
        return 'suburban';
    }

    private determineClassSize(studentStaffRatio: number): string {
        if (studentStaffRatio < 12) return 'small';
        if (studentStaffRatio < 15) return 'medium';
        return 'large';
    }

    private getResearchOpportunities(quality: string): string {
        if (quality === 'world_leading') return 'extensive';
        if (quality === 'excellent') return 'good';
        return 'limited';
    }

    /**
     * Clear cache
     */
    clearCache(): void {
        this.cache.clear();
        this.lastFetch = 0;
    }

    /**
     * Get statistics about UK universities
     */
    getUKStats(): {
        total_universities: number;
        ancient_universities: number;
        russell_group_estimate: number;
        average_international_fees: number;
        top_regions: string[];
    } {
        const ancientCount = UK_UNIVERSITIES.filter(uni => uni.university_type === 'ancient').length;
        const avgFees = UK_UNIVERSITIES.reduce((sum, uni) => sum + uni.tuition_fees_international, 0) / UK_UNIVERSITIES.length;
        const regionCounts = UK_UNIVERSITIES.reduce((acc, uni) => {
            acc[uni.region] = (acc[uni.region] || 0) + 1;
            return acc;
        }, {} as { [key: string]: number });
        
        const topRegions = Object.entries(regionCounts)
            .sort(([,a], [,b]) => b - a)
            .slice(0, 3)
            .map(([region]) => region);

        return {
            total_universities: UK_UNIVERSITIES.length,
            ancient_universities: ancientCount,
            russell_group_estimate: Math.floor(UK_UNIVERSITIES.length * 0.2), // Rough estimate
            average_international_fees: Math.round(avgFees),
            top_regions: topRegions
        };
    }
}

// Export singleton instance
export const ukUniversityDataManager = new UKUniversityDataManager();