<script lang="ts">
	import { onMount } from 'svelte';
	import { Plus, Edit2, Trash2, Search, Building2, Globe } from 'lucide-svelte';

	let { data } = $props();
	let { supabase } = $derived(data);

	let universities = $state<any[]>([]);
	let isLoading = $state(true);
	let searchQuery = $state('');
	
	// Editor Modal State
	let showEditor = $state(false);
	let isEditing = $state(false);
	let currentUniv = $state<any>({});
	
	async function loadUniversities() {
		isLoading = true;
		const { data: u } = await supabase.from('universities').select('*').order('name');
		universities = u || [];
		isLoading = false;
	}

	onMount(() => {
		loadUniversities();
	});

	function openAddModal() {
		isEditing = false;
		currentUniv = {
			id: '',
			name: '',
			country: 'Germany',
			city: '',
			type: 'Public Research',
			tuition_type: 'Zero Tuition',
			acceptance_rate: '',
			global_rank: '',
			living_cost_estimate: '',
			description: '',
			hero_image_url: '',
			logo_url: ''
		};
		showEditor = true;
	}

	async function openEditModal(univ: any) {
		isEditing = true;
		currentUniv = { ...univ };
		showEditor = true;
	}

	async function saveUniversity() {
		try {
			if (isEditing) {
				const { error } = await supabase
					.from('universities')
					.update({
						name: currentUniv.name,
						country: currentUniv.country,
						city: currentUniv.city,
						type: currentUniv.type,
						tuition_type: currentUniv.tuition_type,
						acceptance_rate: currentUniv.acceptance_rate,
						global_rank: currentUniv.global_rank,
						living_cost_estimate: currentUniv.living_cost_estimate,
						description: currentUniv.description,
						hero_image_url: currentUniv.hero_image_url,
						logo_url: currentUniv.logo_url
					})
					.eq('id', currentUniv.id);
					
				if (error) throw error;
			} else {
				// Base ID generation if wanted, otherwise uuid generated by DB
				const payload = {
					name: currentUniv.name,
					country: currentUniv.country,
					city: currentUniv.city,
					type: currentUniv.type,
					tuition_type: currentUniv.tuition_type,
					acceptance_rate: currentUniv.acceptance_rate,
					global_rank: currentUniv.global_rank,
					living_cost_estimate: currentUniv.living_cost_estimate,
					description: currentUniv.description,
					hero_image_url: currentUniv.hero_image_url,
					logo_url: currentUniv.logo_url
				};
				const { error } = await supabase
					.from('universities')
					.insert(payload);
					
				if (error) throw error;
			}

			showEditor = false;
			await loadUniversities();
		} catch (e: any) {
			alert('Error saving: ' + e.message);
		}
	}

	async function deleteUniversity(id: string) {
		if (confirm('Are you sure you want to delete this university? Programs linked to it will retain a null university reference.')) {
			try {
				const { error } = await supabase.from('universities').delete().eq('id', id);
				if (error) throw error;
				await loadUniversities();
			} catch (e: any) {
				alert('Error deleting: ' + e.message);
			}
		}
	}

	const filteredUniversities = $derived(
		universities.filter(u => 
			u.name.toLowerCase().includes(searchQuery.toLowerCase()) || 
			u.country.toLowerCase().includes(searchQuery.toLowerCase())
		)
	);
</script>

<div class="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4">
	<div>
		<h1 class="text-3xl font-bold text-gray-900">Universities</h1>
		<p class="text-sm text-gray-500 mt-1">Manage global university profiles and attributes.</p>
	</div>
	<button onclick={openAddModal} class="bg-yellow-600 hover:bg-yellow-700 text-white px-5 py-2.5 rounded-lg font-bold flex items-center gap-2 transition-colors">
		<Plus size={18} /> Add University
	</button>
</div>

<div class="bg-white border rounded-xl shadow-sm mb-8">
	<div class="p-4 border-b flex items-center gap-3">
		<Search size={18} class="text-gray-400" />
		<input 
			type="text" 
			bind:value={searchQuery}
			placeholder="Search universities by name or country..." 
			class="w-full text-base outline-none bg-transparent"
		/>
	</div>
	<div class="overflow-x-auto">
		<table class="w-full text-left text-sm text-gray-600">
			<thead class="text-xs text-gray-500 uppercase bg-gray-50 border-b">
				<tr>
					<th class="px-6 py-4 font-semibold">University</th>
					<th class="px-6 py-4 font-semibold">Location</th>
					<th class="px-6 py-4 font-semibold">Type</th>
					<th class="px-6 py-4 font-semibold">Tuition Type</th>
					<th class="px-6 py-4 font-semibold text-right">Actions</th>
				</tr>
			</thead>
			<tbody>
				{#if isLoading}
					<tr><td colspan="5" class="px-6 py-8 text-center">Loading...</td></tr>
				{:else if filteredUniversities.length === 0}
					<tr><td colspan="5" class="px-6 py-8 text-center text-gray-400">No universities found.</td></tr>
				{:else}
					{#each filteredUniversities as univ}
						<tr class="border-b hover:bg-gray-50 transition-colors">
							<td class="px-6 py-4 font-bold text-gray-900 flex items-center gap-3">
								{#if univ.logo_url}
									<img src={univ.logo_url} alt="logo" class="w-8 h-8 object-contain rounded border bg-white" onerror={(e) => e.currentTarget.style.display='none'} />
								{:else}
									<div class="w-8 h-8 rounded border bg-slate-100 flex items-center justify-center text-slate-400"><Building2 size={14}/></div>
								{/if}
								{univ.name}
							</td>
							<td class="px-6 py-4">{univ.city}, {univ.country}</td>
							<td class="px-6 py-4">{univ.type}</td>
							<td class="px-6 py-4">
								<span class="inline-block px-2.5 py-1 text-xs font-semibold rounded-full bg-slate-100 text-slate-700">
									{univ.tuition_type}
								</span>
							</td>
							<td class="px-6 py-4 text-right flex justify-end gap-2">
								<button onclick={() => openEditModal(univ)} class="text-blue-600 hover:text-blue-800 p-2 rounded-md hover:bg-blue-50 transition-colors" title="Edit">
									<Edit2 size={16} />
								</button>
								<button onclick={() => deleteUniversity(univ.id)} class="text-red-500 hover:text-red-700 p-2 rounded-md hover:bg-red-50 transition-colors" title="Delete">
									<Trash2 size={16} />
								</button>
							</td>
						</tr>
					{/each}
				{/if}
			</tbody>
		</table>
	</div>
</div>

{#if showEditor}
	<div class="fixed inset-0 bg-gray-900/50 flex items-center justify-center p-4 z-50">
		<div class="bg-white rounded-2xl w-full max-w-4xl max-h-[90vh] overflow-hidden flex flex-col shadow-2xl">
			<div class="px-6 py-4 border-b flex justify-between items-center">
				<h3 class="text-xl font-bold text-gray-900">{isEditing ? 'Edit University' : 'Add New University'}</h3>
				<button onclick={() => showEditor = false} class="text-gray-400 hover:text-gray-600 font-bold text-xl">&times;</button>
			</div>
			
			<div class="p-6 overflow-y-auto flex-1 bg-gray-50">
				<div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
					<!-- Basics -->
					<div class="space-y-4 bg-white p-5 rounded-xl border">
						<h4 class="font-bold text-gray-900 mb-2 border-b pb-2">Core Details</h4>
						<div>
							<label class="block text-xs font-semibold text-gray-500 uppercase mb-1">University Name</label>
							<input type="text" bind:value={currentUniv.name} class="w-full border rounded-lg px-3 py-2 text-sm outline-none focus:border-yellow-500" />
						</div>
						<div class="grid grid-cols-2 gap-4">
							<div>
								<label class="block text-xs font-semibold text-gray-500 uppercase mb-1">Country</label>
								<input type="text" bind:value={currentUniv.country} class="w-full border rounded-lg px-3 py-2 text-sm outline-none focus:border-yellow-500" />
							</div>
							<div>
								<label class="block text-xs font-semibold text-gray-500 uppercase mb-1">City</label>
								<input type="text" bind:value={currentUniv.city} class="w-full border rounded-lg px-3 py-2 text-sm outline-none focus:border-yellow-500" />
							</div>
						</div>
						<div>
							<label class="block text-xs font-semibold text-gray-500 uppercase mb-1">Description</label>
							<textarea bind:value={currentUniv.description} class="w-full border rounded-lg px-3 py-2 text-sm outline-none focus:border-yellow-500 h-24"></textarea>
						</div>
					</div>

					<!-- Categorization & Cost -->
					<div class="space-y-4 bg-white p-5 rounded-xl border">
						<h4 class="font-bold text-gray-900 mb-2 border-b pb-2">Metrics & Categorization</h4>
						<div class="grid grid-cols-2 gap-4">
							<div>
								<label class="block text-xs font-semibold text-gray-500 uppercase mb-1">Type</label>
								<select bind:value={currentUniv.type} class="w-full border rounded-lg px-3 py-2 text-sm outline-none focus:border-yellow-500">
									<option value="Public Research">Public Research</option>
									<option value="Technical University">Technical University</option>
									<option value="Applied Sciences">Applied Sciences</option>
									<option value="Private">Private</option>
								</select>
							</div>
							<div>
								<label class="block text-xs font-semibold text-gray-500 uppercase mb-1">Tuition Type</label>
								<select bind:value={currentUniv.tuition_type} class="w-full border rounded-lg px-3 py-2 text-sm outline-none focus:border-yellow-500">
									<option value="Zero Tuition">Zero Tuition</option>
									<option value="Low Tuition State">Low Tuition State</option>
									<option value="Private">Private</option>
								</select>
							</div>
						</div>
						<div class="grid grid-cols-2 gap-4">
							<div>
								<label class="block text-xs font-semibold text-gray-500 uppercase mb-1">Acceptance Rate</label>
								<input type="text" bind:value={currentUniv.acceptance_rate} placeholder="e.g. 15%" class="w-full border rounded-lg px-3 py-2 text-sm outline-none focus:border-yellow-500" />
							</div>
							<div>
								<label class="block text-xs font-semibold text-gray-500 uppercase mb-1">Global Rank</label>
								<input type="text" bind:value={currentUniv.global_rank} placeholder="e.g. #106" class="w-full border rounded-lg px-3 py-2 text-sm outline-none focus:border-yellow-500" />
							</div>
						</div>
						<div>
							<label class="block text-xs font-semibold text-gray-500 uppercase mb-1">Living Cost Estimate</label>
							<input type="text" bind:value={currentUniv.living_cost_estimate} placeholder="e.g. €950 / month" class="w-full border rounded-lg px-3 py-2 text-sm outline-none focus:border-yellow-500" />
						</div>
					</div>
				</div>

				<!-- Media Links -->
				<div class="bg-white p-5 rounded-xl border">
					<h4 class="font-bold text-gray-900 mb-4 border-b pb-2 flex items-center gap-2">
						<Globe size={16} class="text-blue-500" /> Media & Branding
					</h4>
					<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
						<div>
							<label class="block text-xs font-semibold text-gray-500 uppercase mb-1">Logo URL</label>
							<input type="url" bind:value={currentUniv.logo_url} placeholder="https://..." class="w-full border rounded-lg px-3 py-2 text-sm outline-none focus:border-yellow-500" />
						</div>
						<div>
							<label class="block text-xs font-semibold text-gray-500 uppercase mb-1">Hero Image URL</label>
							<input type="url" bind:value={currentUniv.hero_image_url} placeholder="https://..." class="w-full border rounded-lg px-3 py-2 text-sm outline-none focus:border-yellow-500" />
						</div>
					</div>
				</div>
			</div>
			
			<div class="px-6 py-4 border-t bg-white flex justify-end gap-3">
				<button onclick={() => showEditor = false} class="px-4 py-2 text-sm font-semibold text-gray-600 hover:text-gray-900">Cancel</button>
				<button onclick={saveUniversity} class="px-6 py-2 text-sm font-bold text-white bg-gray-900 hover:bg-black rounded-lg">Save University</button>
			</div>
		</div>
	</div>
{/if}
